### ISSUE TITLE
[JDK-12] : Compilation error in java project

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-java#257]
**Excepted Result:** Gauge init java should should create compilation free project

**Actual Result:** Compilation error exists

**Steps to reproduce:**
1. JDK 12 should be installed
2. Do ``` gauge init java ```
3. open java project in vs code
4. Observe problem sections
 
Getting the below error message:

Unbound classpath container: 'JRE System Library [JavaSE-java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)
]' in project 'JavaProject'
![jdk12Problems](https://user-images.githubusercontent.com/46309201/54981881-6d2cfc00-4fcf-11e9-9e2b-d0b366f73073.JPG)

Kindly find the attached screen shot.

**Environment Details**
Gauge version: 1.0.5.nightly-2019-03-20
Commit Hash: 7aaf683

Plugins
-------
csharp (0.10.6.nightly-2019-03-12)
dotnet (0.1.1)
html-report (4.0.8.nightly-2019-03-08)
java (0.7.2.nightly-2019-03-24)

**Comment by Debashis9012** [comment]
![jdk12Problems](https://user-images.githubusercontent.com/46309201/54981818-48d11f80-4fcf-11e9-8289-bb160701d99d.JPG)

**Comment by nehashri** [comment]
Java 12 is not yet supported by Java VSCode plugin. It has been fixed with https://github.com/eclipse/eclipse.jdt.ls/issues/959. Because of this there are still some errors for a simple gauge java project on VSCode. 
The fix has been done for maven projects - not to rewrite the .classpath files generated by Java VSCode plugin. And to add the correct version of Java while generating .classpatth files.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
``` 0.7.2.nightly-2019-03-28 ```
