### ISSUE TITLE
Publish Javadoc on the web

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge-java#35]
Javadoc for Gauge Java classes (Table, TableRow, BeforeStep, etc.) should be published on the web for all to see. While Gauge Java is not fully documented at this point, posting it online will encourage open source commits to improve it, and also make it easier to use.

**Comment by sriv** [comment]
Javadocs are available here: http://www.javadoc.io/doc/com.thoughtworks.gauge/gauge-java/0.3.1

Please use the same version as the `gauge-java` maven artifact version specified in your `pom.xml`.

Also, please note that javadocs are work in progress, you should see them changing in the upcoming releases. 

Most of the documentation that concerns a user of gauge-java (as opposed to a contributor) should be available in [this package](http://static.javadoc.io/com.thoughtworks.gauge/gauge-java/0.3.1/com/thoughtworks/gauge/package-summary.html).

Thanks for raising this, we should make these resources more explicit.

**Comment by Thunderforge** [comment]
I had asked in Gitter about Javadoc and was told that it didn't exist on the web. I'm glad that it already exists. It certainly should be more explicit and be able to be linked from the main site.

**Comment by sriv** [comment]
To be honest, none of us knew - I was trying to look for a place to put the generated javadocs, and it turned out that javadoc.io was capable of hosting javadocs for artifacts put on maven central, it was just a matter of accessing them. So this is all a very pleasant co-incidence :).

Am closing this issue, but we will continue to improve the docs, possibly with more examples.
