### ISSUE TITLE
Plugin stops to see JAVA_HOME env variable

### ISSUE THREAD

**Issue by nvborisenko** [getgauge/gauge-java#378]
Previously I executed specs via `gague run` and it worked.

After upgrading gauge to v1.0.7 and dependent java plugin, it says that `java is not recognizable program or ...`.

To resolve:
Add java bin path to `path` environment variable.

BUT
`JAVA_HOME` is set.

**Comment by negiDharmendra** [comment]
@nvborisenko Please make sure that the path to `java` executable is available in the `PATH` env

**Comment by nvborisenko** [comment]
I see your point. Doesn't matter that it worked with previous version. Thx.

**Comment by sriv** [comment]
@nvborisenko is right. gauge-java `0.7.3` and below used a [golang based launcher](https://github.com/getgauge/gauge-java/blob/v0.7.3/gauge-java.go), which used to check for [`JAVA_HOME`](https://github.com/getgauge/gauge-java/blob/v0.7.3/gauge-java.go#L39) and [`gauge_java_home`](https://github.com/getgauge/gauge-java/blob/v0.7.3/gauge-java.go#L38) env vars for the java toolchain. 

`0.7.4` got rid of the golang dependency, the newer scripts assume that the `JAVA_HOME/bin` would be in `PATH`. While not unreasonable, this is not intentional. The newer scripts are supposed to mirror the previous launcher.

Reopening this.
