### ISSUE TITLE
Add helper methods in Table type

### ISSUE THREAD

**Issue by apoorvam** [getgauge/gauge-java#41]
From [@kdabir](https://github.com/kdabir), 
A way to access table elements as `table["row name"]["col name"]` will be easy to use. 
This would also make it easy to use with idiomatic way of writing in Groovy.

**Comment by Thunderforge** [comment]
I'd be willing to work on doing this, but I'm not sure I understand what exactly the user is looking for (I'm not familiar with Groovy). What would the method signatures look like?

**Comment by mahendrakariya** [comment]
@Thunderforge We really appreciate your interest in contributing to Gauge!!

I was thinking about how to implement this feature. And it turns out that there is no easy way in Java. The two square brackets syntax is reserved for 2D arrays in Java. Moreover, the indices can't be String. They have to be ints.

So to me it looks like it's not technically feasible to implement this in Java.

**Comment by mahendrakariya** [comment]
Closing this issue since this is not technically feasible.
