### ISSUE TITLE
How to run Spring Boot and Spring Data with Gauge framework

### ISSUE THREAD

**Issue by AhmetRufai** [getgauge/gauge-java#859]
**Is your feature request related to a problem? Please describe.**
Yes, Spring Boot project on Gauge does not work. I'm trying to injection with @Autowired annotation but the injection is not happening. Throwing NullPointerException error.

**Describe the solution you'd like**
When I run the method for db query with Junit, it runs successfully. I specify the annotations below in the class where the method is located. I could not find a similar solution for Gauge.

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class)

Note: Application class is the main class of my project that enables Spring to run.

**Describe alternatives you've considered**
They developed a solution for this situation in the Cucumber framework. A similar solution can be provided. If we cannot solve this problem, unfortunately, we will have to stop using Gauge.

**Additional context**
Hi,
In a large e-commerce company in Turkey, test automation structure, we decided to create using the Gauge Framework. We have created a project structure with spring boot and spring data for our DB connections and queries on the Java side. The Spring infrastructure we have created works successfully when run from the java main class. But when we want to run it with the Gauge runner, Spring does not stand up. Do you have a solution for this situation?

Project structure:
- spec
    - Payment.spec
- src
    - main
        - java
            - model
                -  PaymentEntity.java
            - repository
                - PaymentRepository.java(this class is an interface and extends CrudRepository.java)
            - service
                - PaymentService.java
            - Application.java(main class)
        - resources
            - application.properties
    - test
        - java
            - payment
                - DbCheck.java (I want to perform a db query in this class)
            - step
                - PaymentStep.java (extends DbCheck.java)

Content of the DbCheck Class:
```
package payment;

import Application;
import model.PaymentEntity;
import service.PaymentService;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.List;

@Slf4j
@RunWith(SpringRunner.class)
@SpringBootTest(classes = Application.class)
public class DbCheck {

    @Autowired
    private PaymentService paymentService;

    @Test
    public void checkData() {
        List<PaymentEntity> paymentEntity = paymentService.findAllByBankId(100);
        System.out.println(paymentEntity.toArray());
    }

}
```
Note: It runs successfully when run with JUnit from @Test annotation.

Thanks,
Ahmet

**Comment by chadlwilson** [comment]
These all look like Java 16+ problems. Hopefully they have been addressed now with various fixes and library upgrades, but if people still have similar issues, we can re-open this.

**Comment by AtchutaRao** [comment]
I am working in a Java11+Gauge-java plugin 0.7.3 +gradle+spring  based project. and I was placed beans.xml in the src\test\java and I was able to load the beas.xml through applicationContext.

when I upgrade guage framework to 1.5.6  and gauge-java plug in version 0.10.3 the beans.xml could not load Through classPathXMLApplicationContext.

and I am getting the below error Error Message: org.springFramework.beans.factory.BeanDefinitionStoreException:IOException parsing XML document from classpath resource [beas.xml]; nested exception is java.io.fileNotFoundException.class path resource [beas.xml] can not be opened because it does not exist.

the beans.xml was successfully loaded FileSystemXMLApplicationContext in both versions.

I want to load the beas.xml using classPathXMLApplicationContext by using guage framework to 1.5.6  and gauge-java plug in version 0.10.3
